[2024-05-02T09:13:51.964-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T09:13:51.972-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:09:45.508832+00:00 [queued]>
[2024-05-02T09:13:51.974-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:09:45.508832+00:00 [queued]>
[2024-05-02T09:13:51.974-0500] {taskinstance.py:2303} INFO - Starting attempt 3 of 6
[2024-05-02T09:13:51.979-0500] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-05-02 14:09:45.508832+00:00
[2024-05-02T09:13:51.981-0500] {standard_task_runner.py:63} INFO - Started process 39417 to run task
[2024-05-02T09:13:51.984-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scenario_two_v3', 'second_task', 'manual__2024-05-02T14:09:45.508832+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dotnet_dag.py', '--cfg-path', '/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/tmphvv55esl']
[2024-05-02T09:13:51.985-0500] {standard_task_runner.py:91} INFO - Job 27: Subtask second_task
[2024-05-02T09:13:52.006-0500] {task_command.py:426} INFO - Running <TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:09:45.508832+00:00 [running]> on host nestors-macbook.attlocal.net
[2024-05-02T09:13:52.032-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nestor' AIRFLOW_CTX_DAG_ID='scenario_two_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T14:09:45.508832+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T14:09:45.508832+00:00'
[2024-05-02T09:13:52.032-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T09:13:52.041-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T
[2024-05-02T09:13:52.041-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dotnet run /Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/']
[2024-05-02T09:13:52.045-0500] {subprocess.py:86} INFO - Output:
[2024-05-02T09:13:52.153-0500] {subprocess.py:93} INFO - Couldn't find a project to run. Ensure a project exists in /private/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/airflowtmpliev467h, or pass the path to the project using --project.
[2024-05-02T09:13:52.187-0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-02T09:13:52.188-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T09:13:52.193-0500] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02T09:13:52.202-0500] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=scenario_two_v3, task_id=second_task, execution_date=20240502T140945, start_date=20240502T141351, end_date=20240502T141352
[2024-05-02T09:13:52.206-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task second_task (Bash command failed. The command returned a non-zero exit code 1.; 39417)
[2024-05-02T09:13:52.219-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T09:13:52.225-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T09:13:52.225-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
