[2024-05-02T09:15:53.510-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T09:15:53.519-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:09:45.508832+00:00 [queued]>
[2024-05-02T09:15:53.521-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:09:45.508832+00:00 [queued]>
[2024-05-02T09:15:53.521-0500] {taskinstance.py:2303} INFO - Starting attempt 4 of 6
[2024-05-02T09:15:53.527-0500] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-05-02 14:09:45.508832+00:00
[2024-05-02T09:15:53.529-0500] {standard_task_runner.py:63} INFO - Started process 39445 to run task
[2024-05-02T09:15:53.532-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scenario_two_v3', 'second_task', 'manual__2024-05-02T14:09:45.508832+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dotnet_dag.py', '--cfg-path', '/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/tmpnjizcz6a']
[2024-05-02T09:15:53.534-0500] {standard_task_runner.py:91} INFO - Job 30: Subtask second_task
[2024-05-02T09:15:53.548-0500] {task_command.py:426} INFO - Running <TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:09:45.508832+00:00 [running]> on host nestors-macbook.attlocal.net
[2024-05-02T09:15:53.575-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nestor' AIRFLOW_CTX_DAG_ID='scenario_two_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T14:09:45.508832+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T14:09:45.508832+00:00'
[2024-05-02T09:15:53.575-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T09:15:53.586-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T
[2024-05-02T09:15:53.586-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dotnet run --project /Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj']
[2024-05-02T09:15:53.590-0500] {subprocess.py:86} INFO - Output:
[2024-05-02T09:15:54.636-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.637-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018: System.IO.IOException: The process cannot access the file '/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/bin/Debug/net8.0/dotnetapp.deps.json' because it is being used by another process. [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.637-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.637-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException) [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.637-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.638-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at System.IO.File.Create(String path) [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.638-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.638-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.638-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.638-0500] {subprocess.py:93} INFO - /usr/local/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-02T09:15:54.642-0500] {subprocess.py:93} INFO - 
[2024-05-02T09:15:54.643-0500] {subprocess.py:93} INFO - The build failed. Fix the build errors and run again.
[2024-05-02T09:15:54.648-0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-02T09:15:54.649-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T09:15:54.654-0500] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02T09:15:54.664-0500] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=scenario_two_v3, task_id=second_task, execution_date=20240502T140945, start_date=20240502T141553, end_date=20240502T141554
[2024-05-02T09:15:54.669-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task second_task (Bash command failed. The command returned a non-zero exit code 1.; 39445)
[2024-05-02T09:15:54.683-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T09:15:54.689-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T09:15:54.689-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
