[2024-05-02T09:14:44.284-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T09:14:44.292-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:14:41.582691+00:00 [queued]>
[2024-05-02T09:14:44.294-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:14:41.582691+00:00 [queued]>
[2024-05-02T09:14:44.294-0500] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-02T09:14:44.300-0500] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-05-02 14:14:41.582691+00:00
[2024-05-02T09:14:44.303-0500] {standard_task_runner.py:63} INFO - Started process 39430 to run task
[2024-05-02T09:14:44.306-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scenario_two_v3', 'second_task', 'manual__2024-05-02T14:14:41.582691+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dotnet_dag.py', '--cfg-path', '/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/tmprat6x0ua']
[2024-05-02T09:14:44.307-0500] {standard_task_runner.py:91} INFO - Job 29: Subtask second_task
[2024-05-02T09:14:44.323-0500] {task_command.py:426} INFO - Running <TaskInstance: scenario_two_v3.second_task manual__2024-05-02T14:14:41.582691+00:00 [running]> on host nestors-macbook.attlocal.net
[2024-05-02T09:14:44.349-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nestor' AIRFLOW_CTX_DAG_ID='scenario_two_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T14:14:41.582691+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T14:14:41.582691+00:00'
[2024-05-02T09:14:44.350-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T09:14:44.357-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T
[2024-05-02T09:14:44.357-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dotnet run /Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj']
[2024-05-02T09:14:44.360-0500] {subprocess.py:86} INFO - Output:
[2024-05-02T09:14:44.467-0500] {subprocess.py:93} INFO - Couldn't find a project to run. Ensure a project exists in /private/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/airflowtmpka0eje8_, or pass the path to the project using --project.
[2024-05-02T09:14:44.505-0500] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-02T09:14:44.506-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T09:14:44.512-0500] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/nestoralfaro/Desktop/pbi-scenario-two/py_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02T09:14:44.522-0500] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=scenario_two_v3, task_id=second_task, execution_date=20240502T141441, start_date=20240502T141444, end_date=20240502T141444
[2024-05-02T09:14:44.527-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task second_task (Bash command failed. The command returned a non-zero exit code 1.; 39430)
[2024-05-02T09:14:44.548-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T09:14:44.554-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T09:14:44.554-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
